### ISSUE TITLE
 Error in get_hadK function when quantizing Falcon-7B model 

### ISSUE THREAD

**Issue by huangwei021230** [Cornell-RelaxML/qtip#16]
Hello,

I am trying to extend the qtip repository to support Falcon-7B model and encountered an issue during quantization. Specifically, while using `qtip/lib/utils/matmul_had.py` in the `get_hadK` function, I encountered the following error:

```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/qtip/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/qtip/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/Code/gptq/qtip/qtip/quantize_falcon/quantize_finetune_falcon.py", line 75, in quantize_llama_decoder
    finetune.quantize_finetune_decoder_layer(layer, quant_order, idx, cb, args,
  File "/root/autodl-tmp/Code/gptq/qtip/qtip/lib/algo/finetune.py", line 176, in quantize_finetune_decoder_layer
    utils.matmul_hadUt(W.T.to(device) * SV).T * SU)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Code/gptq/qtip/qtip/lib/utils/matmul_had.py", line 90, in matmul_hadUt
    return matmul_hadU(X, transpose=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Code/gptq/qtip/qtip/lib/utils/matmul_had.py", line 69, in matmul_hadU
    hadK, K = get_hadK(n, transpose)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Code/gptq/qtip/qtip/lib/utils/matmul_had.py", line 61, in get_hadK
    assert (is_pow2(n))
            ^^^^^^^^^^
AssertionError
```

The error occurs because the n parameter passed to get_hadK is 4672 and the hidden size of Falcon-7B is 4544, both of which do not satisfy the conditions required by this function.

Unfortunately, I am not clear about the exact purpose of the get_hadK function and the expected handling of n in this context. 

Could you kindly explain how this function is designed to handle this case, or whether there is a way to resolve this error given the unique characteristics of Falcon-7B's architecture?

I would greatly appreciate your help in understanding the logic behind this function and how to fix the issue.

Thank you!

**Comment by tsengalb99** [comment]
get_hadK gets the "small Hadamard matrix" described in the QuIP# paper. You'll either need to find a Hadamard matrix of size 4*73 for 4672 and 4*71 for 4544, use the FFT version described in QuIP#, or do outlier channel splitting to pad the weight matrices to a "nice number." If the matrices are fusable, you can do something like Quarot/Spinquant and generate any orthogonal matrix that makes the matrix incoherent and then fuse it into the preceding layer.
